name: BlockShuffle
version: '${project.version}'
main: com.ronlab.blockshuffle.BlockShufflePlugin
api-version: '26.1'

dependencies:
  server:
    RonlabGameAssistant:
      load: BEFORE
      required: false
      join-classpath: true
